import {
  app,
  BrowserWindow,
  desktopCapturer,
  dialog,
  ipcMain,
} from "electron";
import { inputService } from "./main/inputService";
import { Action } from "./main/types";
import type { AccessibilityPermissionsResult, MacOSEventHook } from "iohook-macos";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

// Store main window reference for IPC
let mainWindow: BrowserWindow | null = null;

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: true,
      contextIsolation: false,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();

  // Clean up reference when window is closed
  mainWindow.on("closed", () => {
    mainWindow = null;
  });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
ipcMain.handle("getSources", async () => {
  return await desktopCapturer.getSources({ types: ["screen"] });
});

ipcMain.handle("showSaveDialog", async () => {
  return await dialog.showSaveDialog({
    buttonLabel: "Save video",
    defaultPath: `vid-${Date.now()}.webm`,
  });
});

ipcMain.handle("getOperatingSystem", () => {
  return process.platform;
});

// Input capture IPC handlers
ipcMain.handle(
  "startInputCapture",
  async (_event, sessionId: string, sessionStartTime: number) => {
    try {
      await inputService.start(
        sessionId,
        sessionStartTime,
        (action: Action) => {
          // Forward action to renderer
          if (mainWindow && !mainWindow.isDestroyed()) {
            mainWindow.webContents.send("action", action);
          }
        }
      );
      return { success: true as const };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.error("Failed to start input capture:", message);
      return { success: false as const, error: message };
    }
  }
);

ipcMain.handle("stopInputCapture", () => {
  inputService.stop();
  return { success: true };
});

// Permission check for accessibility (required for global input capture on macOS)
ipcMain.handle("checkAccessibilityPermission", () => {
  if (process.platform === "darwin") {
    try {
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      const iohook = require("iohook-macos") as MacOSEventHook;
      const permissions: AccessibilityPermissionsResult =
        iohook.checkAccessibilityPermissions();
      return {
        granted: permissions.hasPermissions,
        platform: "darwin",
        message: permissions.message,
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      return { granted: false, platform: "darwin", message };
    }
  }
  // On other platforms, assume permission is granted
  return { granted: true, platform: process.platform };
});
